### ISSUE TITLE
OCR gives RestError

### ISSUE THREAD

**Issue by restacksyj** [Azure-Samples/cognitive-services-quickstart-code#222]
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Running readTextFromUrl() gives out a new RestError and printRecText just prints "Recognized Text:"

### Any log messages given by the failure
> at new RestError (/Users/yashjajoo/Documents/js_projects/music_extract/node_modules/@azure/ms-rest-js/dist/msRest.node.js:2460:28)
    at /Users/yashjajoo/Documents/js_projects/music_extract/node_modules/@azure/ms-rest-js/dist/msRest.node.js:3662:37
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: undefined,

### Expected/desired behavior
> 

### OS and Version?
> macOS Big Sur

### Versions
>

**Comment by v-jaswel** [comment]
Hello @restacksyj,

First I apologize for my delayed reply.
When I run the Computer Vision JavaScript sample at https://github.com/Azure-Samples/cognitive-services-quickstart-code/blob/master/javascript/ComputerVision/ComputerVisionQuickstart.js, I am unable to reproduce the issue you are seeing.
Can you tell me what URL you are passing to readTextFromUrl()?
Also, if you have made any changes to the code from the sample, can you post your version? That might also help me reproduce the issue.

Thank you,
v-jaswel

**Comment by v-jaswel** [comment]
Hello,

I am going to close this for now as there has been no activity for a while, but please feel free to reopen it if needed.
Thank you,
v-jaswel
